   var dependencies = {
    links:
      [
            { "source" : "AlcoholViewController", "dest" : "PopUpViewController" },
            { "source" : "AppDelegate", "dest" : "OnboardingContentViewController" },
            { "source" : "AppDelegate", "dest" : "OnboardingViewController" },
            { "source" : "FoodClassificationTableViewController", "dest" : "FoodItem" },
            { "source" : "FoodTableViewController", "dest" : "PopUpViewController" },
            { "source" : "main", "dest" : "AppDelegate" },
            { "source" : "MainTableViewController", "dest" : "PopUpViewController" },
            { "source" : "ResultsViewController", "dest" : "BTSpiderPlotterView" },
            { "source" : "SleepViewController", "dest" : "PopUpViewController" },
            { "source" : "SleepViewController", "dest" : "Timer" },
            { "source" : "AlcoholViewController", "dest" : "PopUpViewController" },
            { "source" : "AlcoholViewController", "dest" : "AlcoholicDrinkTableViewCell" },
            { "source" : "AlcoholViewController", "dest" : "AppDelegate" },
            { "source" : "AppDelegate", "dest" : "OnboardingViewController" },
            { "source" : "AppDelegate", "dest" : "OnboardingContentViewController" },
            { "source" : "ExerciseTableViewController", "dest" : "AppDelegate" },
            { "source" : "FoodClassificationTableViewController", "dest" : "FoodItem" },
            { "source" : "FoodTableViewController", "dest" : "PopUpViewController" },
            { "source" : "FoodTableViewController", "dest" : "AppDelegate" },
            { "source" : "MainTableViewController", "dest" : "PopUpViewController" },
            { "source" : "MainTableViewController", "dest" : "SettingsTableViewController" },
            { "source" : "MainTableViewController", "dest" : "ResultsViewController" },
            { "source" : "MainTableViewController", "dest" : "BTSpiderPlotterView" },
            { "source" : "MainTableViewController", "dest" : "AppDelegate" },
            { "source" : "OnboardingSettingsTableViewController", "dest" : "AppDelegate" },
            { "source" : "ResultsViewController", "dest" : "BTSpiderPlotterView" },
            { "source" : "ResultsViewController", "dest" : "AppDelegate" },
            { "source" : "SettingsTableViewController", "dest" : "SettingsViewController" },
            { "source" : "SettingsTableViewController", "dest" : "AppDelegate" },
            { "source" : "SleepViewController", "dest" : "Timer" },
            { "source" : "SleepViewController", "dest" : "PopUpViewController" },
            { "source" : "SleepViewController", "dest" : "AppDelegate" },
         ]
    }
  ;
