# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'Onboard'

target 'Kenkou' do

end

target 'KenkouTests' do

end

target 'KenkouUITests' do

end

